# Generated by Django 4.2 on 2023-12-21 22:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('road', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('extra_info', models.CharField(max_length=40)),
                ('zip_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
