# Generated by Django 4.2 on 2024-03-04 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_address_alter_ecommerceclient_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecommerceclient',
            name='password',
            field=models.CharField(max_length=256),
        ),
    ]
