# Generated by Django 4.2 on 2024-03-20 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_address_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecommerceclient',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='ecommerceclient',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
