# Generated by Django 4.2 on 2024-03-20 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_ecommerceclient_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecommerceclient',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ecommerceclient',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
