# action.yml
name: 'Ecommerce API run'
description: 'Runs the docker instance.'
#inputs:
#  who-to-greet:
#    description: 'Who to greet'
#    required: true
#    default: 'World'
#outputs:
#  time: # id of output
#    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile-api-local'
