FROM python:3.10

ENV PYTHONUNBUFFERED 1
RUN apt-get clean && apt-get -y update
RUN mkdir /code
ADD ./requirements /requirements/
RUN pip install -r requirements/requirements.txt

ADD ./api /code/
COPY ./entrypoint-local.sh /
WORKDIR /code