# Generated by Django 4.2 on 2023-12-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='related_tags',
            field=models.ManyToManyField(blank=True, to='selling.tag'),
        ),
    ]
