# Generated by Django 3.2 on 2023-06-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products_matching', to='selling.Tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='related_tags',
            field=models.ManyToManyField(blank=True, related_name='_selling_tag_related_tags_+', to='selling.Tag'),
        ),
    ]
