# Generated by Django 4.2 on 2023-12-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='products',
            field=models.ManyToManyField(related_name='products_in_cart', to='selling.shoppingcartproduct'),
        ),
    ]
