# Generated by Django 3.2 on 2023-09-18 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
