# Generated by Django 4.2 on 2023-12-23 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0003_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizing',
            name='size_short',
            field=models.CharField(max_length=8),
        ),
    ]
