# Generated by Django 4.2 on 2023-12-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0005_alter_sizing_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('extra_text', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
