# Generated by Django 4.2 on 2024-01-02 22:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_address_alter_ecommerceclient_options_and_more'),
        ('selling', '0006_shippingoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.address')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selling.paymentmethod')),
                ('shipping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selling.shippingoption')),
                ('shopping_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='selling.shoppingcart')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
