# Generated by Django 4.2 on 2024-01-10 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0008_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
    ]
