# Generated by Django 4.2 on 2024-01-11 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0009_remove_product_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['type']},
        ),
    ]
